imitation_objective:
  _target_: nuplan.planning.training.modeling.objectives.multiple_imitation_objective.MultipleImitationObjective
  _convert_: 'all'

  weight: 1.0                  # weight contribution to the overall loss
